image: node:latest

stages:
  - frontend-build
  - frontend-test

frontend-build:
  type: deploy
  stage: frontend-build
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_FRONTEND --api-key=$HEROKU_API_KEY

frontend-test:
  stage: frontend-test
  script: 
    - npm install
    - npm test
